# Generated by Django 5.1.4 on 2024-12-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='working_date',
            field=models.DateField(blank=True, null=True, verbose_name='作業日'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='end_time',
            field=models.TimeField(verbose_name='作業終了時間'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='start_time',
            field=models.TimeField(verbose_name='作業開始時間'),
        ),
    ]
