# Generated by Django 5.1.4 on 2024-12-14 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0002_dailyreport_working_date_alter_dailyreport_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='genba.profile'),
        ),
    ]
