# Generated by Django 5.1.4 on 2024-12-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0003_dailyreport_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='workers', to='genba.profile'),
        ),
    ]
