# Generated by Django 5.1.4 on 2024-12-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0004_dailyreport_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='select_types',
            field=models.CharField(blank=True, choices=[('請負', '請負'), ('乗用', '乗用')], max_length=50, verbose_name='請負乗用'),
        ),
    ]
