# Generated by Django 5.1.4 on 2024-12-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0005_dailyreport_select_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='highway_payment',
            field=models.CharField(blank=True, choices=[('現金', '現金'), ('カード', 'カード'), ('電子マネー', '電子マネー'), ('会社ETC', '会社ETC'), ('無', '無')], max_length=50, verbose_name='高速料金'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='hotel',
            field=models.CharField(blank=True, max_length=100, verbose_name='宿泊料金'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='parking',
            field=models.CharField(blank=True, max_length=100, verbose_name='駐車料金'),
        ),
    ]
