# Generated by Django 5.1.4 on 2024-12-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0006_alter_dailyreport_highway_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='select_types',
            field=models.CharField(blank=True, choices=[('請負', '請負'), ('常用', '常用')], max_length=50, verbose_name='請負乗用'),
        ),
    ]
