# Generated by Django 5.1.4 on 2024-12-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genba', '0007_alter_dailyreport_select_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='select_types',
            field=models.CharField(blank=True, choices=[('請負', '請負'), ('常傭', '常傭')], max_length=50, verbose_name='請負乗用'),
        ),
    ]
